const DROUGHT = 6;
const DUST_AND_HAZE = 7;
const WILDFIRE = 8;
const FLOODS = 9;
const SEVERE_STORMS = 10;
const VOLCANOES = 12;
const WATER_COLOR = 13;
const LANDSLIDES = 14;
const SEA_AND_LAKE_ICE = 15;
const EARTHQUAKES = 16;
const SNOW = 17;
const TEMPERATURE_EXTREMES = 18;
const MANMADE = 19;

export {
  DROUGHT,
  DUST_AND_HAZE,
  WILDFIRE,
  FLOODS,
  SEVERE_STORMS,
  VOLCANOES,
  WATER_COLOR,
  LANDSLIDES,
  SEA_AND_LAKE_ICE,
  EARTHQUAKES,
  SNOW,
  TEMPERATURE_EXTREMES,
  MANMADE,
};
